KMACHINE = "qemuarm64"

require conf/machine/qemuarm64.conf

MACHINEOVERRIDES =. "qemuarm64:"
KMACHINE = "qemuarm64"

PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
UBOOT_MACHINE = "qemu_arm64_defconfig"

SERIAL_CONSOLES = "115200;ttyAMA0"
