BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"

BBFILE_COLLECTIONS += "company"

BBFILE_PATTERN_company = "^${LAYERDIR}/"

BBFILE_PRIORITY_company = "6"

LAYERSERIES_COMPAT_company = "scarthgap"