DISTRO = "companydistro"
DISTRO_NAME = "Company Distro"

DISTRO_VERSION = "0.1"

PACKAGE_CLASSES = "package_ipk"

INIT_MANAGER = "systemd"

DISTRO_FEATURES += "systemd virtualization seccomp"

VIRTUAL-RUNTIME_init_manager = "systemd"

# ADD FOR DOCKER: uncomment for docker approach
# VIRTUAL-RUNTIME_container_manager = "docker"

EXTRA_IMAGE_FEATURES += "allow-empty-password empty-root-password"

USER_CLASSES ?= "buildstats"

PATCHRESOLVE = "noop"

INHERIT += "rm_work"

LICENSE_FLAGS_ACCEPTED = "*"